---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAqEOxN8bXpt5aOvCzxrn6pbhhs3Q9irM2Zi/oNMkPvFp3DnOQB5+YBb0eqzb/5m+4MKV8JtFWTTg9EwbnPUBDTJ8hcVBt+uIVXm64LoftYWOmu/VaasLtNtE8u6g2IG44X2jfsDEr1WQk2JwtVLkWWAwiU8wCTBs6aeTQ+U/Etm3M6Jmp+AK/CxGtDryVdg0e17TGzVnOdQyYKlzXpxrVilg5KU1AOm56/Jsk8fJB2/JGqNUOM52F9zV3L2NTtBuaTbj/+IIxa9BuWK6/ob8OT/BrwbL/dTHbIBnohtaOpDO3qTc3gsN5LFQtWjmWazJ4gNeaYQYwBtOxhlqM669TCNvLtbBe/uJwdZwUp9QTC2at3vFzYoDUVAd6xApBwde/VROG73WCKSepqoL2o13+U1wZOfwJt7ER2O+nHRHF5JdTGdL6dhcDfB0Irpnu+Ndi4b62tukENi7FDTJmGDkXwg2FS0numNLDxjybPMMSmIwGJ/xTIgOKnrP8Li9kOxfPnIzh2S4fzogMXEMqsN3H+XX3XKMTq3IT4ZRn2MTTMoHP0QmiKksM6f4hQKfXA2bOb7TfkuUdQkyHb2GxTA3han77eou1/E5WKFNcyoTNUS6h6zAUpf7MeZZ1BghEodeQABjUNU3Lu8LuqycqAfs7X2xDEFMOJYTD6xk3rzgzZ8vk0IapT+JjQ4y+gNq0qAUV+WKk0oi1FVP31
    MONGO_INITDB_ROOT_USERNAME: AgB0I9RneiwELiOyxDtZKTXTe9M7pHISQRbPxn/u5r28mEMLPj0yOgz9jDC6eM8w++oaSarxhdJrkv4mT0CWcmT42E4xv+L+IqJjEzl/wTN9QHLCCyqr51f5OQKrmzWTu1zHcUhmokQbvb8b5Vc62me+/w4tQ0QDifiHnpRpgdzFGa+rplbb8wxwfac9RjHzPs/9itwB7ams4sPgpgRkVlw3BJSnux7huAT+C+FlWi1KCYKJ1kVrQgUVos03jGEotj8BU2ozRvh0dmvUdI2Vw75X4H9IK27Rq8WfpTI4Qn8/CxLUM/97wnxSWDaD4jsX9twycO+v7chaquNmpbzqGpNZ3lVryVI/vzbNcwS9jZauACcFv60guxs54i/iI5X+kJ7Zi75irRgXo99lw6o6LrT21RSvti5m3LwQwgC3/WDLjseBf/XASz4SBSU8uq/0Gd/iad/os+PvfFfaYrOj3/FIldsf2BY7VyTfqDc/gCLAfaVy6aDwJ6J4c0b33eqqhJXOWRAioMeqrj/POkCjCslCt8BJlHraCE63k71PRnX+hxO/iMP1yXHaWOFklzDjjqPjQjZ0B1OorlMgp2WHBlQvyw9oPR0hH61gE33aPzCGdrA27HBBT5bLEXUlW7qxnWTpJmXy2xALzZMfqj9rGKSxDPqiTnOHVRYJALq1yq1jUXarOexTcK1jx86rbJ6+KNDcKK+owg==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
