---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-new
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgBJXVy0NJGbAqG6o76lW/lJa5XNlq0ZGZ+YZJ/rGk9pIXdcQP0tYVJE5C5vxbiecW7WOHE9A8cyJHSgavG92XMX8nxpSH0gIqiViIfEZ0Im19Pj8SP6wfXL3XQDNHtymEfbY3E5JkLVVzKs/4IqwyUmLbj4swpHH4CrsAl7upAW3tCFHKV4FRXmtq1wlDeWI/ipuJgU8v0fKZgo7eT7w2hB1RDhukRre8730tXNhxVse3w+zZpzTcnV1uu2m8n3rCF96VCJPTzQ4wF28jTe7HCgLh4fXeMk3tkq6stbi05gmLV6k8SCRfJMtS3iWTMRQ/CboK+oQVjSfTLx9N2VYT/Wp/uTnehyBfaZi7ExGmFWKyAFpvEHwq9x8ojSafOsEk1v/znC5O4t5axExNxNkHmC8cpfbF2Jjg+7SQkytbdnzs6bM3dFFOTQ3AoOvW7f9zLllxSaxyysbd+lbDNTV4vqvBM3w4ROLe4+ktAUeJ/6guJ58ankdWd/HgH0VCkHvtyfFNWoaP6GEbXSAF4Eo9qOJwT/UdnT/E3VbVn/5/crnrXwwpvSQWeC0TmBhYN8LFHwOeGXtFLPqW3ikjZEnRnyLTOWaWBS0TxOc2eh5xlkLxJjEMs0b4W0bgkN8QIdzKc5q6KlNL3a7ejSBYDHZySHdrQQ4DYqdkmeGZ4qyMmMYaFhwO7+lRSHEBJTYy3GVnv4XnAM8T8XxZWVl+AsvX0r6XILoWHUJUSjlOaorII9rWqjkf6TnG3wXdU89t8manWFGTve83htTRlqu9mLdNrIhDzV7k9JeGDg9eGbfscTZ1lLYJXUeVQ2l44YcEct6z7UTK9szDfOsQ==
  template:
    metadata:
      name: backend-secrets-new
      namespace: default
