---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgB7SJroZJ/2Z66vhyH7vUzx5o60wNrfS92Qe/s8bew78VwsJFGOK0ULZ4MHihluMp7E4TwVbHqV3pTLEKQARavAS+yaEWx2rI0UgY8zjX4FoUTkH3IBVYLev6G2m4GYsKwLexpfw1ISJY5KtAP1gWqHljl4Nc+CSl4UbRFvTpJkytP69ups8wZ6cXaET0LtvI3k4Lv8gXcvu4gpKrh4px+jVMXfz/3g2gqCtzY7QxQHpxZBbqaLw/TMCBlasqLFfFcZDiJJuAAn9rYydTWnNxUixSEziCuHWdone284Fkl/nTU3/rDChmonVfj4V8c/N7io0ziuacsV/Bkq5Bee4vxSkDKUMBzbXaLGUSvSjkPpBYYlBl0OC39DLfmiIHYHi3R+Yev984yQRFPC+Ck+cY5L93pIo7YTjbuV5fHbZ/aaiJRHwBcLbO81N06d30vnXBoaHZlSqfBROcImBS44BQRUmqtQ+I1Zx8bX+ZLilSDZbH6K1PjkWKW+GNxVV5anqwM27Zo82mPbElJQgrNFu3eAtAumVF3nsUhA7zJujxviWr0TboJsxvl0/CR7mY3hSkQgZO/Vi2CYJnYMVioxMzOh8PMxqNxzIbGT5jovOyNdkjM/0gpiqSTBqnBOFQ1+V0Tn/EC01T9dIUR7yTHRbXtT1oW292vQxlxwxEj4SEGaVNqM7rNHAvivEf/ECF7gQ2MGXG9YDQfGJOQLdi88UoVBsdE816d7em/4teYvTp5mzIsfLBWX2bffGqOgAmT+S3B8MBkH3vauoSgoJqv36NwDTH+gQw==
  template:
    metadata:
      name: backend-secrets
      namespace: default
