---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCvEcfKWaCzc6Z1f1XIgZXbCQShphcOqPXhkkufZH5oV3NDRVn9XFgLBKI8imrh7b4O8ZNcRNmmGzI8vErG9HGbURFTxRPlgxxlPtK//0zdnuo+g3zR+3U+VKpBdOSurbBH9niyuuIrb81pHiQnkv/4ME3DvV5MUXqhI3BI/tYQTxDqAHJQ2Y7SXlzQ+Nnh2nQ8nMVtZ5BNZPv2E+wJMwNnr9GPwE3XWtTm4yk3mu6yjj0UN79FDY/riWtINZg59YTZe8H/SxNNuJ1iEIxi50mCQp6JgFkg25S47Q4JPEcGlYREBwHHpB8MNB7aRbg9DQjx/bJd7+5do/P3u4qu7aTzyvDy8XK299cG7ByqIP/pkEs89dzNRdpd/RLXU3SIV7uQsx1T2C03LRX/jvlB4fsisFWnoy5aw2ubizCh+CovsxZea05RjSJBiVdNaS57xs6OwpxZARwRO0ztmaj9JTHUuaenr/XQlSA0x0heiJHHH2jYPOVA2VDAutCUyJq++e6dC3qelywQSPCMb2/tvtir/bVq8qFgMqibWBKtdA2n+45r4dGzR5y9k0Ibr4YCbCuvH0688A5EZMp11LlGQYlTlLUCaJ4LWoWAAo6UuDtf72CjKw3rsf+BV8aThne/2xnykTQHziCAjYClfjzXenadzV016yPGYOoIcydVXYYFcXVnwQJOmYeKVho3fo/+b8xMUAJFsJz28iwA9s8I9bz3DTAuxPseXbtzLatzevwhDZJpMSD/EZTiC+vLj0P0x+L2Tr8v0M49oJISOAJuJfd87CHucalXyKqrTbr0KMyB38XraJUu8BH5hgDL2C/0UsnnYU7ZAx60WQ==
  template:
    metadata:
      name: backend-secrets
      namespace: default
