---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCg7twSuLH/URMUuyliiwevZNWlyLeSdpHddZ/XH07Y1TE8uX6OSADkd0QTsLnwrX3awi/iCZ9nkPkttkElTkWci8Mxyh5j8guXL0SzbXvsungHGzQQYzAn4og6y59+Sn/A5dRO5/bwJHiq6WwWxLhRjRX5q/07B0YdR93sHDL6q5U3GDaqtE6KLVfdiQcUTo772/yil/KQ4QXXMgJKwNkny0RNnDWFcY9cXXLc/ofSlumqPXWAgrABMRLAICFNS8r0tRBxXZXPNWMc3n82+rmW4sLUY2iCM3W24MTTT3EpiC5AYQ3pub+5vhK1QTCv5fO/O2koIpbv83CXrHJQ6PYSR3SFy/UbUdFOtTmTwaryCPZiJDfeD50hxO4o+5CdIxp0HY92xfH64C/k6H/Z0illrirQYFWVM3dqDm1fRv4roIV9uP03dI+gnNjWAjHbaKxsXI3DSeBlz/4LWuoCXPSswRBEEkYeMZi+HyKWUAVqp6J0gCDya6Kp+pJwfCHDzyd+Y1DZP5wPNqs0BUPfE8bA7UgUgkrz4eOzl9eTRTVWIzSWiDk/1YNU1ZyqyCcN+nG62MYDYfA9iUOSH6WT0c0Uuz1GlbrncySjrYR0LMMqWKlGxcbnwbIEVzPKl79FYZEyBG2Yd4D7OpfL/SWUIxSw2jW8sfze6JkNKEbpSPmiffDK84NP2at3m2kArKLD5LEbphuyKcPJgHKM
    MONGO_INITDB_ROOT_USERNAME: AgB3Sp/tHaHYtACcAN6WxYZx1wzPZdqVcgf9Txje5senbY0Q7uqI/jV70S/ElDsjULI/BMn3Ib9KQWJG7ReLJtCB1Y8gD3xexjvvzKMkDPZ82jHCswEh9TO5g7riqoerPwoGVKSGkAdPyvTalsTYHXOXx37fYxcL0MS7FYiZuSnKdW1IwfyDzqsYB884+zuVli/L8EbJNfXKvssrOFe84C8ry2BHyFroUDM3FhOoyyC5GJI5wJwTshfT6g5RXRehHsm+fqmBJ30juSydlLZgXfdS1zLfii7+70iOXbPBBimuWUpUdadCwKGywoyjVBdEOln52A4d1XCxJTS3qAMIkuFDKdBqgglbG54k4k1sRS0hSnlnO9i0uI8Ikh5J4O3yRuudTW/q66cdKgChPpEiMvVzSsPXFZDgCw/YyTxj+D+ZkeH8d+mueuHyUIsQrLzGES7mbzaZeLSuv4Yyfoo6P2aPcCe2kjg6EjvhYtw6w3CyPD+jlc7EcfMOHKaTqiFz5a5tA6D4U57Y+eWZzAbQnSnKJpL5PFbHJUEtBl9Vpp36kAG/Mw31rHFJ+OJfEpc88SKbcQ+ZZg4IJD/3ojdu4HvjMHoMER4q3MHA7J3Z3MTZAbl82EVV+Ue2KJ7uzKyT594+jf5AECquF1Sxmakwi/TldEKvT8h2T/lTCKjTJXYjWGIJN1lpCKXMYUMUS2SKEa65wJElqw==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
